"use strict";

// The mock catalog client matches a query only by its tag comment and replays
// hand-written rows, so no mock test can notice the SQL changing what it selects
// or how PostgreSQL types the result. Both real defects found so far were exactly
// that: `name[]` aggregated without a text cast arrives as the literal "{a,b}",
// and the readers then degrade quietly. This suite is the oracle for that class.
// It runs every catalog query against a live server and asserts the driver-decoded
// shape of each column still matches the committed fixture.

const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const test = require("node:test");

const LIVE = process.env.OKF_POSTGRES_LIVE_TEST === "1" && Boolean(process.env.DATABASE_URL);

const catalogSql = require("../src/catalog");

const SCHEMA = "okf_shape";

// Exercises every column the catalog queries project, so a shape comparison is
// never decided by a null.
const SEED_SQL = `
DROP SCHEMA IF EXISTS ${SCHEMA} CASCADE;
CREATE SCHEMA ${SCHEMA};
COMMENT ON SCHEMA ${SCHEMA} IS 'Application data';

CREATE TYPE ${SCHEMA}.order_status AS ENUM ('pending', 'paid', 'cancelled');
COMMENT ON TYPE ${SCHEMA}.order_status IS 'Lifecycle states for an order';

CREATE TABLE ${SCHEMA}.customers (
  id bigserial PRIMARY KEY,
  email text NOT NULL UNIQUE,
  email_normalized text GENERATED ALWAYS AS (lower(email)) STORED
);
COMMENT ON TABLE ${SCHEMA}.customers IS 'Registered customers';
COMMENT ON COLUMN ${SCHEMA}.customers.id IS 'Customer identifier';
COMMENT ON COLUMN ${SCHEMA}.customers.email IS 'Login email';
COMMENT ON COLUMN ${SCHEMA}.customers.email_normalized IS 'Search-normalized email';

CREATE TABLE ${SCHEMA}.orders (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  customer_id bigint NOT NULL,
  status ${SCHEMA}.order_status NOT NULL DEFAULT 'pending',
  CONSTRAINT orders_pkey PRIMARY KEY (id),
  CONSTRAINT orders_customer_id_fkey FOREIGN KEY (customer_id)
    REFERENCES ${SCHEMA}.customers(id) ON DELETE CASCADE DEFERRABLE,
  CONSTRAINT orders_id_positive CHECK (id > 0)
);
COMMENT ON TABLE ${SCHEMA}.orders IS 'Customer orders';
COMMENT ON COLUMN ${SCHEMA}.orders.customer_id IS 'Owning customer';
COMMENT ON COLUMN ${SCHEMA}.orders.status IS 'Order lifecycle state';
CREATE INDEX orders_customer_id_idx ON ${SCHEMA}.orders (customer_id);

CREATE VIEW ${SCHEMA}.order_summary AS
SELECT customer_id, count(*) AS order_count FROM ${SCHEMA}.orders GROUP BY customer_id;
COMMENT ON VIEW ${SCHEMA}.order_summary IS 'Order totals by customer';
`;

// Which exported statement backs each fixture key, and whether it is parameterised
// by the selected schemas.
const QUERIES = [
  ["database", "DATABASE_SQL", false],
  ["schemas", "SCHEMAS_SQL", true],
  ["allschemas", "ALL_SCHEMAS_SQL", false],
  ["relations", "RELATIONS_SQL", true],
  ["columns", "COLUMNS_SQL", true],
  ["constraints", "CONSTRAINTS_SQL", true],
  ["indexes", "INDEXES_SQL", true],
  ["enums", "ENUMS_SQL", true],
];

// A shape is what a reader can actually branch on: null carries no information,
// and every other value is either an array or a scalar of some JS type.
function shapeOf(value) {
  if (value === null || value === undefined) return null;
  if (Array.isArray(value)) return `array<${value.length ? shapeOf(value[0]) || "unknown" : "empty"}>`;
  if (value instanceof Date) return "date";
  return typeof value;
}

// Arrays disagree only on element type when one side happened to be empty.
function compatible(left, right) {
  if (left === right) return true;
  if (!left || !right) return false;
  const bare = (s) => (s.startsWith("array<") ? "array" : s);
  if (bare(left) !== bare(right)) return false;
  return left.includes("empty") || right.includes("empty");
}

function shapesForRows(rows) {
  const shapes = new Map();
  for (const row of rows) {
    for (const [column, value] of Object.entries(row)) {
      const shape = shapeOf(value);
      if (shape && !shapes.has(column)) shapes.set(column, shape);
    }
  }
  return shapes;
}

test("every catalog query decodes to the shape the committed fixture claims", { skip: LIVE ? false : "set OKF_POSTGRES_LIVE_TEST=1 and DATABASE_URL" }, async (t) => {
  const { Client } = require("pg");
  const fixture = JSON.parse(fs.readFileSync(
    path.join(__dirname, "fixtures/query-results.json"),
    "utf8",
  ));

  const client = new Client({
    connectionString: process.env.DATABASE_URL,
    application_name: "okf-postgres-live-shape",
  });
  await client.connect();
  t.after(async () => {
    try {
      await client.query(`DROP SCHEMA IF EXISTS ${SCHEMA} CASCADE`);
    } finally {
      await client.end();
    }
  });
  await client.query(SEED_SQL);

  const failures = [];
  for (const [key, constant, parameterised] of QUERIES) {
    const text = catalogSql[constant];
    assert.equal(typeof text, "string", `${constant} must be exported`);

    const live = await client.query({ text, values: parameterised ? [[SCHEMA]] : [] });
    assert.ok(live.rows.length > 0, `${key}: the seed must produce at least one row`);

    const liveShapes = shapesForRows(live.rows);
    const fixtureShapes = shapesForRows(fixture[key] || []);

    // The fixture must not describe a column the query no longer returns.
    for (const column of fixtureShapes.keys()) {
      if (!live.fields.some((field) => field.name === column)) {
        failures.push(`${key}.${column}: in fixture but not returned by the query`);
      }
    }
    for (const field of live.fields) {
      if (!Object.prototype.hasOwnProperty.call(fixture[key][0] || {}, field.name)) {
        failures.push(`${key}.${field.name}: returned by the query but absent from the fixture`);
      }
    }
    for (const [column, liveShape] of liveShapes) {
      const fixtureShape = fixtureShapes.get(column);
      if (fixtureShape && !compatible(liveShape, fixtureShape)) {
        failures.push(`${key}.${column}: server decodes as ${liveShape}, fixture claims ${fixtureShape}`);
      }
    }
  }

  assert.deepEqual(failures, [], `fixture no longer matches the live server:\n  ${failures.join("\n  ")}`);
});

test("aggregated name columns reach the driver as arrays, not array literals", { skip: LIVE ? false : "set OKF_POSTGRES_LIVE_TEST=1 and DATABASE_URL" }, async (t) => {
  const { Client } = require("pg");
  const client = new Client({
    connectionString: process.env.DATABASE_URL,
    application_name: "okf-postgres-live-shape-arrays",
  });
  await client.connect();
  t.after(async () => {
    try {
      await client.query(`DROP SCHEMA IF EXISTS ${SCHEMA} CASCADE`);
    } finally {
      await client.end();
    }
  });
  await client.query(SEED_SQL);

  const constraints = await client.query({ text: catalogSql.CONSTRAINTS_SQL, values: [[SCHEMA]] });
  const primaryKey = constraints.rows.find((row) => row.constraint_name === "orders_pkey");
  const foreignKey = constraints.rows.find((row) => row.constraint_name === "orders_customer_id_fkey");

  // Without a text cast these arrive as the literal "{id}" and every reader that
  // expects a list silently sees none.
  assert.ok(Array.isArray(primaryKey.columns), `primary key columns decoded as ${typeof primaryKey.columns}: ${JSON.stringify(primaryKey.columns)}`);
  assert.deepEqual(primaryKey.columns, ["id"]);
  assert.ok(Array.isArray(foreignKey.columns), `foreign key columns decoded as ${typeof foreignKey.columns}`);
  assert.deepEqual(foreignKey.columns, ["customer_id"]);
  assert.ok(Array.isArray(foreignKey.referenced_columns), `referenced columns decoded as ${typeof foreignKey.referenced_columns}`);
  assert.deepEqual(foreignKey.referenced_columns, ["id"]);

  const enums = await client.query({ text: catalogSql.ENUMS_SQL, values: [[SCHEMA]] });
  const status = enums.rows.find((row) => row.type_name === "order_status");
  assert.ok(Array.isArray(status.values), `enum values decoded as ${typeof status.values}: ${JSON.stringify(status.values)}`);
  assert.deepEqual(status.values, ["pending", "paid", "cancelled"]);
});
