"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const { spawnSync } = require("node:child_process");
const { Client } = require("pg");
const { producePostgres } = require("../src/producer");

const SEED_SQL = `
COMMENT ON DATABASE okf_test IS 'OKF PostgreSQL live compatibility database';
CREATE SCHEMA IF NOT EXISTS okf_sales;
COMMENT ON SCHEMA public IS 'Application data';
COMMENT ON SCHEMA okf_sales IS 'Sales reference data';
CREATE TABLE IF NOT EXISTS okf_sales.accounts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL
);
COMMENT ON TABLE okf_sales.accounts IS 'Customer billing accounts';
COMMENT ON COLUMN okf_sales.accounts.id IS 'Billing account identifier';
DO $$ BEGIN
  CREATE TYPE public.okf_live_status AS ENUM ('pending', 'paid', 'shipped');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
COMMENT ON TYPE public.okf_live_status IS 'Lifecycle of a live order';
CREATE TABLE IF NOT EXISTS public.okf_live_orders (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id bigint NOT NULL,
  status public.okf_live_status NOT NULL DEFAULT 'pending',
  total numeric(12,2) NOT NULL CHECK (total >= 0),
  CONSTRAINT okf_live_orders_account_fkey
    FOREIGN KEY (account_id) REFERENCES okf_sales.accounts(id)
    ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED
);
COMMENT ON TABLE public.okf_live_orders IS 'Orders used for OKF producer compatibility';
COMMENT ON COLUMN public.okf_live_orders.account_id IS 'Owning billing account';
CREATE INDEX IF NOT EXISTS okf_live_orders_account_idx ON public.okf_live_orders(account_id);
CREATE OR REPLACE VIEW public.okf_live_order_summary AS
SELECT account_id, count(*) AS order_count
FROM public.okf_live_orders
GROUP BY account_id;
COMMENT ON VIEW public.okf_live_order_summary IS 'Order totals by billing account';
`;

async function liveSmoke() {
  if (process.env.OKF_POSTGRES_LIVE_TEST !== "1") {
    throw new Error("Set OKF_POSTGRES_LIVE_TEST=1 to seed and inspect the dedicated okf_test database.");
  }
  const connectionString = process.env.DATABASE_URL;
  if (!connectionString) throw new Error("DATABASE_URL is required.");

  const client = new Client({ connectionString, application_name: "okf-postgres-live-smoke-seed" });
  await client.connect();
  try {
    const current = await client.query("SELECT current_database() AS name");
    if (current.rows[0] && current.rows[0].name !== "okf_test") {
      throw new Error("Live smoke refuses to seed any database except okf_test.");
    }
    await client.query(SEED_SQL);
  } finally {
    await client.end();
  }

  const output = fs.mkdtempSync(path.join(os.tmpdir(), "okf-postgres-live-"));
  try {
    const result = await producePostgres({
      connectionEnv: "DATABASE_URL",
      source: "live-postgres",
      bundle: "live-postgres",
      schemas: ["public", "okf_sales"],
      output,
    }, { environment: { DATABASE_URL: connectionString } });

    const database = fs.readFileSync(path.join(output, "database.md"), "utf8");
    const schema = fs.readFileSync(path.join(output, "schemas/okf_sales.md"), "utf8");
    const orders = fs.readFileSync(path.join(output, "tables/public/okf_live_orders.md"), "utf8");
    assert.match(database, /OKF PostgreSQL live compatibility database/);
    assert.match(schema, /Sales reference data/);
    assert.match(orders, /Owning billing account/);
    assert.match(orders, /\.\.\/okf_sales\/accounts\.md/);
    assert.match(orders, /ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED/);
    assert.match(orders, /\*\*okf_live_orders_pkey\*\*: primary key \(`id`\)/);
    assert.match(orders, /\*\*okf_live_orders_account_fkey\*\*: foreign key \(`account_id`\).*\(`id`\)/);

    // node-postgres returns an uncast name[] as a raw "{a,b}" string, which the
    // catalog reader would quietly drop. Only a live driver proves the decode.
    const enumType = fs.readFileSync(path.join(output, "types/public/okf_live_status.md"), "utf8");
    assert.match(enumType, /Lifecycle of a live order/);
    for (const label of ["pending", "paid", "shipped"]) {
      assert.match(enumType, new RegExp(`- <code>${label}</code>`));
    }
    assert.equal(result.enums, 1);

    const validator = path.resolve(__dirname, "../../okf-mcp/bin/okf-mcp.js");
    if (!fs.existsSync(validator)) throw new Error(`Sibling okf-mcp validator is required: ${validator}`);
    const validation = spawnSync(process.execPath, [validator, "--root", output, "validate"], { encoding: "utf8" });
    if (validation.status !== 0) {
      process.stderr.write(validation.stdout || "");
      process.stderr.write(validation.stderr || "");
      throw validation.error || new Error("Live PostgreSQL bundle failed okf-mcp validation.");
    }
    process.stdout.write(`${JSON.stringify({ ...result, validated: true }, null, 2)}\n`);
  } finally {
    fs.rmSync(output, { recursive: true, force: true });
  }
}

liveSmoke().catch((error) => {
  process.stderr.write(`${error.stack || error.message}\n`);
  process.exitCode = 1;
});
